;DOS 1.0+ get stdin
;dosile STDREAD
DOS_INT_1:
	MOV AH, READKEY_B
	INT KEYB_SERVICE	;Read the keyboard
	CALL EMITCHAR
	MOV BL, AL
	MOV AX, REGISTER_AX
	MOV AL, BL		;Mask the registers with one another
	MOV REGISTER_AX, AX	;Write it back
	JMP END_INT

;DOS 1.0+ write character to stdout
DOS_INT_2:
	MOV AX, REGISTER_DX
	MOV AH, PUTCHAR
	INT TEXT_SERVICE
	JMP END_INT

EMITCHAR:
	MOV AH, PUTCHAR
	CMP AL, 13
	JE IS_CR
	CMP AL, 8
	JE IS_BS
	INT TEXT_SERVICE
FINISH_EMIT:
	RET

IS_CR:	
	PUSH AX
	INT TEXT_SERVICE
	MOV AL, 10
	INT TEXT_SERVICE
	POP AX
	JMP FINISH_EMIT

IS_BS:
	PUSH AX
	INT TEXT_SERVICE
	MOV AL, ' '
	INT TEXT_SERVICE
	POP AX
	INT TEXT_SERVICE
	JMP FINISH_EMIT
